[package]
name = "dcli"
version = "0.2.0"
edition = "2021"
description = "Play Doom quickly and easily"
authors = ["Paul"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# https://github.com/johnthagen/min-sized-rust
[profile.release]
opt-level = "z"  # Optimize for size.

[dependencies]
toml = "0.8"
tokio = { version = "1.32", features = ["macros", "rt-multi-thread"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sqlx = { version = "0.7", features = [
    "runtime-tokio-native-tls",
    "sqlite",
    "chrono",
] }
eyre = "0.6"
color-eyre = { version = "0.6", default-features = false }
log = "0.4"
log4rs = "1"
colored = "2"
strum = "0.25"
strum_macros = "0.25"
walkdir = "2.3"
indicatif = "0.17"
powershell_script = "1.1"
regex = "1.9"
tabled = "0.14"
inquire = "0.6"
clearscreen = "2"
plist = "1.5"
shlex = "1.2"
