name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: | 
        cd console
        cargo build --verbose
    - name: Run tests
      run: |
        cd console
        cargo test --verbose
    - name: Clippy
      run: |
        cd console
        cargo clippy --verbose -- -D warnings
